### ISSUE TITLE
编译后的文件微信开发者工具直接报错

### ISSUE THREAD

**Issue by eeokee** [cantonjs/wxapp-boilerplate#1]
不能使用

流程
1.克隆
2.yarn
3.yarn start
4.添加dist到微信开发工具目录

报错
![image](https://user-images.githubusercontent.com/3079825/27071479-ba63efd2-504f-11e7-8ad9-ce7d445414c6.png)

**Comment by eeokee** [comment]
环境：
系统 win10x64
node v7.5.0
微信web开发者工具 v0.17.172600

**Comment by Cap32** [comment]
看起来是 windows 路径的问题，我手头上暂时没有 windows。

我更新了一下 webpack 配置，重新 clone 一下项目看看问题是否得到解决了？

**Comment by eeokee** [comment]
@Cap32 确实是这个问题。并且wxapp-webpack-plugin插件编译的js也存在类似问题。

**Comment by Cap32** [comment]
能否提供错误信息？

**Comment by Cap32** [comment]
刚刚 2295db8eb1ee707f8de266611fb8fa3276fdf7e3 升级了 `wxapp-webpack-plugin`，修复了对 windows 的兼容性问题

**Comment by eeokee** [comment]
好，虽然已经弃坑了，下个项目在试试

**Comment by julytian** [comment]
@Cap32 ，依然是window平台，下载最新的代码了,`yarn run build`打包之后微信开发工具 同样碰到一样的报错，控制台报如下错:
```js
ERROR in ./src/components/user/user.js

F:\webfe\wxapp\wxapp-boilerplate\src\components\user\user.js
  2:1  error  'Component' is not defined  no-undef

```

**Comment by Cap32** [comment]
@julytian 感谢指出。

我把这个问题创建了新的 issue https://github.com/cantonjs/wxapp-boilerplate/issues/15 ，最新版已经修复了
