### ISSUE TITLE
import的模板文件和wxss路径问题

### ISSUE THREAD

**Issue by yautah** [cantonjs/wxapp-boilerplate#10]
src如果我创建了templates目录用于存放template的wxml和wxss文件
pages中例如index.wxml和index.wxss文件分别进行了import

编译后：
1. wxml会编译到dist根目录下，自动添加hash名
2. wxss丢失了

问题似乎出在loader上

**Comment by Cap32** [comment]
> wxml会编译到dist根目录下，自动添加hash名

`.wxml` 文件编译后目录是会有所不同，你可以在 webpack config 上通过配置相应的 file-loader 调整输出目录或文件名。

但正如在 web 前端项目使用 webpack 一样，个人认为只要不影响结果和调试，其实不需要太关心编译后 dist 的文件和路径，因为编译后的文件可读性一般都会比 src 要差很多。

> wxss丢失了

`.wxss` 暂时确实会丢失 `@import` 的文件，原因是暂时没有 `wxss-loader` 之类的 loader 来处理 `.wxss` 文件。

解决办法仍然有很多。例如，据我所了解 wxss 兼容 sass/scss （也兼容 less 和 stylus） 语法，而 sass 有现成 loader 会默认处理 `@import`，所以你可以通过增加 `sass-loader` 来编译 `.wxss` 文件，或者把 `.wxss` 后缀修改为 `.scss` ，来解决问题。
