### ISSUE TITLE
关于watch的问题

### ISSUE THREAD

**Issue by cz848** [cantonjs/wxapp-boilerplate#11]
我发现这个项目只有主入口文件在每次修改后重新生成，其它文件都是除非遇到语法错误，否则无论怎么修改都不会自动生成呢？有什么其它诀窍吗？
系统是macos 10.12.6，webpack 3.5.4/3.5.5

**Comment by Cap32** [comment]
是 webpack 没有重新编译还是微信小程序开发者工具没有重新编译？我的开发环境是 macOS 10.12.5， webpack 3.5.5，微信开发者工具 v0.20.191900，没有遇到这个问题。

如果是微信开发者工具没有重新编译，尝试重启再试试。

**Comment by cz848** [comment]
抱歉一开始我没有搞清楚，我看了下，是webpack编译界面看起来没有任何变化（包括lint检查也没有任何输出），但是开发者工具还是检测到了文件变化的。

**Comment by Cap32** [comment]
webpack 编译界面可以根据个人喜好修改 stats 配置来输出结果 https://webpack.js.org/configuration/stats/
