### ISSUE TITLE
打包后common.js体积过大。

### ISSUE THREAD

**Issue by Cobain93** [cantonjs/wxapp-boilerplate#12]
开发的时候，项目体积164kb。编译完以后，common体积巨大。总共有292kb，请问要如何优化。
之前使用fis3的时候，编译后只增加了10KB，想哭啊。。
下面是我的webpack配置

const WXAppWebpackPlugin = require('wxapp-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
const path = require('path');
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const { NODE_ENV } = process.env;
const APP_NAME = process.env.APP_NAME;
const DIST = process.env.DIST || 'wechat-scan';
const DEBUG = NODE_ENV !== 'production';
const PRODUCTION = NODE_ENV === 'production';
const LINT = true;

const createRelativeFile = (outputPath, ext = '[ext]') => ({
    publicPath: (file) => `../../${file}`,
    outputPath: outputPath,
    name: `/[name].[hash:8].${ext}`
});

export default {
    entry: {
        app: [
            `es6-promise/dist/es6-promise.auto${DEBUG ? '.min' : ''}.js`,
            `./${APP_NAME}/utils/bomPolyfill.js`,
            `./${APP_NAME}/app.js`
        ]
    },
    output: {
        filename: '[name].js',
        publicPath: '/',
        path: path.resolve(`../${DIST}/${APP_NAME}`)
    },
    module: {
        rules: [{
            test: /\.js$/,
            include: [
                path.resolve(`./${APP_NAME}`)
            ],
            use: [
                'babel-loader',
                LINT && 'eslint-loader'
            ].filter(Boolean)
        }, {
            test: /\.wxs$/,
            include: [
                path.resolve(`./${APP_NAME}`)
            ],
            use: [{
                loader: 'file-loader',
                options: createRelativeFile('wxs', 'wxs')
            },
                'babel-loader',
                LINT && 'eslint-loader'
            ].filter(Boolean)
        }, {
            test: /\.(jpe?g|png|gif|svg)$/,
            include: [
                path.resolve(`./${APP_NAME}`)
            ],
            loader: 'file-loader',
            options: createRelativeFile('images')
        }, {
            test: /\.scss$/,
            include: [
                path.resolve(`./${APP_NAME}`)
            ],
            use: [{
                loader: 'file-loader',
                options: {
                    useRelativePath: true,
                    name: '[name].wxss'
                }
            }, {
                loader: 'sass-loader',
                options: {
                    includePaths: [
                        path.resolve(`./${APP_NAME}/styles`),
                        path.resolve(`./${APP_NAME}`)
                    ]
                }
            }]
        }, {
            test: /\.wxss$/,
            include: [
                path.resolve(`./${APP_NAME}`)
            ],
            use: [{
                loader: 'file-loader',
                options: {
                    useRelativePath: true,
                    name: '[name].wxss'
                }
            }]
        }, {
            test: /\.wxml$/,
            include: path.resolve(`${APP_NAME}/pages`),
            use: [{
                loader: 'file-loader',
                options: {
                    useRelativePath: true,
                    name: '[name].[ext]'
                }
            }, {
                loader: 'wxml-loader',
                options: {
                    root: path.resolve(`./${APP_NAME}`)
                }
            }]
        }, {
            test: /\.wxml$/,
            include: path.resolve(`./${APP_NAME}`),
            exclude: path.resolve(`./${APP_NAME}/pages`),
            use: [{
                loader: 'file-loader',
                options: createRelativeFile('wxml')
            }, {
                loader: 'wxml-loader',
                options: {
                    root: path.resolve(`./${APP_NAME}`)
                }
            }]
        }]
    },
    plugins: [
        new CleanWebpackPlugin([ `../${DIST}/${APP_NAME}` ]),
        new WXAppWebpackPlugin(),
        new webpack.optimize.ModuleConcatenationPlugin(),
        PRODUCTION && new webpack.optimize.UglifyJsPlugin({
            warnings: false,
            ie8: false,
            ecma: 7,
            compress: true
        }),
        new CopyWebpackPlugin([{
            from: `./${APP_NAME}/*.json`,
            to: `../`
        }, {
            from: `./${APP_NAME}/*.MD`,
            to: `../`
        }])
    ].filter(Boolean),
    // devtool: PRODUCTION ? false : 'source-map',
    devtool: false,
    resolve: {
        modules: [path.resolve(__dirname, APP_NAME), 'node_modules']
    }
};

**Comment by Cap32** [comment]
单凭这个 webpack 配置很难定位问题所在。建议使用 https://github.com/th0r/webpack-bundle-analyzer 或类似工具检查一下
