### ISSUE TITLE
希望开源wxapp-webpack-plugin或者更新下

### ISSUE THREAD

**Issue by zhyc9de** [cantonjs/wxapp-boilerplate#13]
小程序公测了[自定义组件](https://developers.weixin.qq.com/blogdetail?action=get_post_info&docid=34fde56e6ee55dac840952f4bf46cbfb&lang=zh_CN)

wxapp-webpack-plugin目前不会自动搜索`components`文件夹下的内容，没开源想提pr也没办法，希望作者支持下新功能~

**Comment by Cap32** [comment]
其实有开源，并且即将发布新版支持 components https://github.com/Cap32/wxapp-webpack-plugin/pull/5

**Comment by zhyc9de** [comment]
哦哦，不好意思没找到~

**Comment by Cap32** [comment]
c8a71db91d36dd374ac89f84c9d0feb104a79ef4 开始支持 `Compoents`，或者直接在项目里更新 [wxapp-webpack-plugin](https://github.com/Cap32/wxapp-webpack-plugin) 致 `v0.16.0` 或以上版本即可
