### ISSUE TITLE
支付宝小程序运行报错

### ISSUE THREAD

**Issue by mxh861001** [cantonjs/wxapp-boilerplate#18]
```
 start:alipay或者build:alipay后,运行报错如下
```
### app.js
```js
App({
	onLaunch(options) {
		console.log('App Launch', options);
		console.log('getSystemInfoSync', my.getSystemInfoSync());
		console.log('SDKVersion', my.SDKVersion);
		console.log('launch');
	},
	onShow() {
		console.log('show');
	},
	onHide() {
		console.log('hide');
	},
	globalData: {
		hasLogin: false,
	}
});
```

![qq 20180109134205](https://user-images.githubusercontent.com/9146759/34706691-197f9b12-f544-11e7-92d3-cef413d37966.png)

**Comment by jiachenmu** [comment]
同上,我也遇到了这个问题,请问楼上解决了吗?.

**Comment by mxh861001** [comment]
@jiachenmu  没有,弃这个了

**Comment by jiachenmu** [comment]
@mxh861001  好吧,兄台有推荐的其他框架,可以一套代码应用于支付宝和微信小程序吗😬

**Comment by mxh861001** [comment]
@jiachenmu 没有,分开写的

**Comment by jiachenmu** [comment]
@mxh861001  好的, 3Q

**Comment by Cap32** [comment]
是由于 promise polyfill 导致的，新版支付宝小程序已经内置支持 promise 了，去掉这行即可解决 https://github.com/cantonjs/wxapp-boilerplate/blob/514c457344d829d5de3f85043ca7120c6456b71c/webpack.config.babel.js#L43

最新版已经修复了这个问题。
