### ISSUE TITLE
为什么是scss？

### ISSUE THREAD

**Issue by Windancer** [cantonjs/wxapp-boilerplate#2]
我的项目用了less，在使用wxapp-webpack-plugin的时候运行报错，是不是需要把wxss当做scss而不是less？

**Comment by Windancer** [comment]
我的项目用了less，在使用wxapp-webpack-plugin的时候运行报错，是不是也是这个原因？需要把wxss当做scss而不是less？

**Comment by Cap32** [comment]
你可以 fork 一下，然后根据自己习惯或需求修改
