### ISSUE TITLE
wxml 路径引入不正确

### ISSUE THREAD

**Issue by ldwonday** [cantonjs/wxapp-boilerplate#20]
在页面wxml里引入wxml文件夹下的toast下的index.wxml：`<import src="../../../wxml/toast/index.wxml"/>`
结果编译出来的路径不正确：`<import src="../../wxml/toast/index.wxml"/>`少了一个层级，具体应该是webpack里面的file-loader哪里的问题，这个有解决方案吗？

**Comment by ldwonday** [comment]
具体可以在模板项目pages里面新建一个二级目录，引入
<import src="../../../wxml/motto/motto.wxml"/>
<wxs src="../../../wxs/powered.wxs" module="powered" />
编译后发现
<import src="../../wxml/motto/motto.wxml"/>
<wxs src="../../wxs/powered.wxs" module="powered" />
路径不正确

**Comment by ldwonday** [comment]
另外还有很多小问题，例如在开发环境下`<button formType="submit"/>`是正确的，但是build之后，就不行了除非写成`<button form-type="submit"/>`

**Comment by Cap32** [comment]
`wxml-loader` >= v0.2.0 和 `file-loaer` >= v1.1.11 解决了这些问题，`file-loader` 
和 `wxml-loader` 配置均有所改变，可以参考 https://github.com/cantonjs/wxapp-boilerplate/blob/f6413bab3405a0c0dfb34a6ffa21757e51619d99/webpack.config.babel.js#L18-L25 和 https://github.com/cantonjs/wxapp-boilerplate/blob/f6413bab3405a0c0dfb34a6ffa21757e51619d99/webpack.config.babel.js#L85-L94
