### ISSUE TITLE
window下所有的路径编译后有问题

### ISSUE THREAD

**Issue by ldwonday** [cantonjs/wxapp-boilerplate#21]
如题，在window下路径都编译成了`..\..\`，导致图片，模版等运行不了，应该不是反斜杠。

**Comment by ldwonday** [comment]
上一个版本没有这个问题啊

**Comment by ldwonday** [comment]
https://github.com/webpack-contrib/filhttps://github.com/webpack-contrib/file-loader/issues/256e-loader/issues/256

**Comment by Cap32** [comment]
升级 [wxml-loader >= v0.2.1 ](https://github.com/Cap32/wxml-loader/releases/tag/v0.2.1) 修复了这个问题，已发布至 `npm`

十分感谢 👍🏿

**Comment by leamiko** [comment]
nice
