### ISSUE TITLE
请问现有的纯原生小程序可以植入进这个脚手架吗

### ISSUE THREAD

**Issue by duanpf** [cantonjs/wxapp-boilerplate#23]
请问现有的纯原生小程序可以植入进这个脚手架吗

**Comment by Cap32** [comment]
你把源代码放入 `src` 目录应该就可以了，你试试看

**Comment by Cap32** [comment]
你把源代码放入 `src` 目录应该就可以了，你试试看

**Comment by duanpf** [comment]
可以的，在小程序里使用的是/imgs/xxxx  这样的根路径，植入后图片就引入失败了
![1523434703 1](https://user-images.githubusercontent.com/24790085/38605250-51b7724e-3da5-11e8-993f-66b584982301.jpg)
还有个问题，本来打算使用mpvue，但是侵入性太强，全部vue语法，出问题了只有等美团给答案，但是又不愿意牺牲es6和webpack的一些工程化的方案，所以想请问下这个可以作为开发生产环境的项目吗

**Comment by Cap32** [comment]
> 在小程序里使用的是/imgs/xxxx 这样的根路径，植入后图片就引入失败了

源代码里面引用图片是 `src="/imgs/xxxx"` 来引用的吗？webpack 从 2.0 开始不支持绝对路径引用，试试改为 `imgs/xxxx` 或相对路径看看？

> 还有个问题，本来打算使用mpvue，但是侵入性太强，全部vue语法，出问题了只有等美团给答案，但是又不愿意牺牲es6和webpack的一些工程化的方案，所以想请问下这个可以作为开发生产环境的项目吗

这个脚手架和语法无关，开发者既可以用原生的语言开发，也可以通过添加 `loaders` 和 `plugins` 来实现个性化开发，但需要掌握 webpack 的基本用法

**Comment by Cap32** [comment]
Close issue for no response. Feel free to reopen it if still have this problem.
