### ISSUE TITLE
微信小程序 上传和预览时，显示此错误，怎么处理

### ISSUE THREAD

**Issue by duanpf** [cantonjs/wxapp-boilerplate#25]
![image](https://user-images.githubusercontent.com/24790085/39564721-f3d155ba-4ee7-11e8-80ee-c057f8aca3c5.png)

**Comment by jaceechan** [comment]
.map只是调试需要的文件，忽略即可，不影响功能

**Comment by Cap32** [comment]
执行 `yarn build` 命令打包不会生成 .map 文件。`.map` 文件用于 `sourcemap` 调试，只是适用于开发环境，不适用于 `production` 环境
