### ISSUE TITLE
微信小程序，经常遇到打包后，Page()未正确调用，然后重新打包，刷新了几次，又莫名的会变好，想问下这个问题是什么原因呢

### ISSUE THREAD

**Issue by duanpf** [cantonjs/wxapp-boilerplate#26]
![image](https://user-images.githubusercontent.com/24790085/39681504-39b273be-51dd-11e8-945a-0ab615b54a63.png)

**Comment by jaceechan** [comment]
请可以详细描述一下操作的步骤吗？执行了什么命令，在什么时候打开微信开发者工具等

**Comment by duanpf** [comment]
我测试了下发现，只要我调整app.json里面的pages数组中的顺序后，数组中第一个页面始终会报上面说的这个错误，
![image](https://user-images.githubusercontent.com/24790085/39688739-c1b642da-5206-11e8-88a7-3c313d22e052.png)

**Comment by jaceechan** [comment]
app.json的顺序和这个问题关系不大，只是影响报错上的显示，因为工具试从数组第一个的页面开始执行的，发现错误就报错并无法执行下去，所以这个关系不大。 我这里暂时无法重现问题，所以麻烦提供一下详细的操作步骤，以便重现问题并解决，谢谢

**Comment by Cap32** [comment]
Close for no response. Feel free to reopen it if still have this problem.
