### ISSUE TITLE
已关注，又不懂的，请教下

### ISSUE THREAD

**Issue by yellowStar1992** [cantonjs/wxapp-boilerplate#27]
es6-promise/dist/es6-promise.auto${isDev ? '.min' : ''}.js  这句是什么意思？

**Comment by yellowStar1992** [comment]
能加个联系方式么

**Comment by jaceechan** [comment]
isDev为true时 最终输出的是es6-promise/dist/es6-promise.auto.min.js

**Comment by yellowStar1992** [comment]
大佬 有群么，目前 我们公司 需要构建一个自动化构建工具，我用gulp写完，但是效果不理想，自己也是首次接触webpack，过了一遍文档，看到你们开源的这个项目，很幸福，正在看

**Comment by Cap32** [comment]
Webpack 入门有点难，所以才有这个 boilerplate 项目，降低搭建开发环境成本。如果需要个性化开发，得先花时间掌握 webpack 使用技巧。

有问题可以在这里提交 issue，作者会尽量抽时间提供帮助。
