### ISSUE TITLE
为什么只能在wxapp-boilerplate目录下成功，换个目录名就总是各种报错

### ISSUE THREAD

**Issue by Windancer** [cantonjs/wxapp-boilerplate#3]

**Comment by Cap32** [comment]
请提供详细的错误信息。另外这个项目仅能提供基础的脚手架或示例代码，若要在这个项目基础之上开发，你需要有 npm, webpack, babel 等前端项目开发的基础

**Comment by Windancer** [comment]
感谢回复，您可以自己clone下来然后cd 目录之前换个名字再安装依赖和运行看看结果。

**Comment by Cap32** [comment]
没报错

**Comment by Windancer** [comment]
[报错说明](http://file.40017.cn/shtrain/interTrainTicket/static/images/transfer-miniprogram/QQ图片20170710142619.png)

**Comment by Cap32** [comment]
是安装 node_sass 时候提示缺少 python2 路径的错误。如果你在未切换目录前能安装成功，那你可能是切换目录时切换了磁盘导致环境变量缺失。如果你在项目上习惯使用 less 的话，建议可以把 sass/scss 替换为 less，less 的安装比 sass 简单
