### ISSUE TITLE
求助： <template is="motto" data="{{motto:motto}}" />，motto:motto的意义？

### ISSUE THREAD

**Issue by smartymoon** [cantonjs/wxapp-boilerplate#34]
刚接触这个脚手架，平时写PHP比较多。看到下面这行有点懵
` <template is="motto" data="{{motto:motto}}" />`
`motto:motto` 中的冒号是什么东西？本来以为是本很简单的问题，各种检索之后没有找到相关介绍。
试验后发现，冒号后的东西有默认值的感觉，那 `motto:motto` 看起来完全没有意义啊

看起来很简单的问题，却找不到答案，折磨人。还请赐教

**Comment by Cap32** [comment]
这是模版引用的语法 https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxml/import.html

这里的 `data={{motto:motto}}` 类似于为 `data` 赋予了一个  `{ "motto": motto }` 的对象，冒号前后分别是 key:value。至于有没有默认值我没找到相关文档。

希望能帮到你吧
