### ISSUE TITLE
windows下用就是坑，运行都运行不了，这样真的好嘛……

### ISSUE THREAD

**Issue by Windancer** [cantonjs/wxapp-boilerplate#4]
windows环境clone下来，运行成功，但是控制台报错！！！！
[图片](http://file.40017.cn/shtrain/interTrainTicket/static/images/transfer-miniprogram/2.png)

**Comment by Cap32** [comment]
> 通过微信开发者工具，添加 dist 目录到项目上

请看清楚 README，你添加的是 src 目录。

写 issue 态度请好一点。不过我还是建议你别使用这个项目了。谢谢你的反馈。🙂

**Comment by Windancer** [comment]
你只适合跟懂你的人打交道，但总有问题需要你提前排除，而不是别人提出来。
如果我什么都自己搞好，我用你这个框架干什么？就不能过渡平滑友好一点嘛？
你可知道，我经历着多大的困扰。唉，你只顾着怪别人不懂你。
