### ISSUE TITLE
支付宝小程序构建失败

### ISSUE THREAD

**Issue by xiao0502** [cantonjs/wxapp-boilerplate#40]
clone下来的代码，无论是npm run start:alipay，还是npm run build，在支付宝小程序开发工具里面跑不起来。

表现： 
[CONFIG] user config: {}
C:\Users\ADMINI~1.USE\AppData\Local\Temp\.alipay-tiny\alipay\out-development
Starting the development server...
Compiled successfully!
Development is ready!
http://127.0.0.1:8136/
Note that the development build is not optimized.

TypeError: Cannot read property 'WorkerComponent' of undefined
./components/user/user.js
internal:///components/user/user.js:4:16
  1 | 
  2 | import { WorkerComponent as $Component } from '@alipay/af-appx';
  3 | 
> 4 | var Component = $Component || function(){};
    |                ^  5 |   
  6 | Component(
  7 | { 

希望能够跑起来.

node 8.9.4  window 64位

**Comment by Cap32** [comment]
这看起来是 `import { WorkerComponent as $Component } from '@alipay/af-appx';` 的问题。请检查一下 `@alipay/af-appx` 是否安装并正确引用？
