### ISSUE TITLE
微信小程序转百度小程序时对 wxs 的处理

### ISSUE THREAD

**Issue by HOUCe** [cantonjs/wxapp-boilerplate#44]
wxs 是微信小程序所特有的，类似提供 filter 等特性。

在基于微信小程序转百度小程序时，对于微信小程序的 wxs 文件如何处理？

或者有什么思路，我来提 PR

**Comment by Cap32** [comment]
Duplicated with https://github.com/Cap32/wxml-loader/issues/15

**Comment by HOUCe** [comment]
感谢回复。如果采用类似的webpack plugin方式，将 wxs 导出为主 js 脚本，可行性如何

**Comment by Cap32** [comment]
纯粹个人意见不值得这么做，原因有二：

1. 因为百度小程序是模版数据暂时只能从逻辑层 Page 中 data 对象来，所以 plugin 的工作不仅仅是从 wxs 导出为 js 脚本，还需要修改逻辑层 Page 的 data 对象，视图模版才能获得数据，这样开发难度和调试都不太容易；
2. 相信百度小程序未来也会推出 wxs 类似的替代方案；

欢迎讨论 😀

**Comment by HOUCe** [comment]
cool, 我去 push 一下百度手百团队。

百度官方也在小黑屋开发「搬家工具」，思路是 AST  做转换，html 用的 stricter-htmlparser2   js 用的 babel-traverse

**Comment by Cap32** [comment]
Great job 👍🏿
