### ISSUE TITLE
关于wxss文件的webpack配置问题

### ISSUE THREAD

**Issue by Somnusochi** [cantonjs/wxapp-boilerplate#5]
如果项目里面引用了第三方的小程序库像`weui`这类的，需要引用一个`weui.wxss`的文件，如果是`less``scss``stylus`之类的是可以使用webpack对应的loader，但`wxss`文件不知道怎么处理好，使用了`css-loader`发现有问题，如果方便希望可以解答下

**Comment by Cap32** [comment]
用 `file-loader` 即可。

已更新 [webpack.config.babel.js](https://github.com/cantonjs/wxapp-boilerplate/blob/master/webpack.config.babel.js) 里面增加了对直接引用 `.wxss` 文件的支持。

**Comment by Somnusochi** [comment]
感谢，后来自己发现了

**Comment by sandysong** [comment]
楼上能正常用么？我在app.wxss里@import weui.wxss，但是并没有把内容加载进来，也没有把文件拷贝过去
