### ISSUE TITLE
压缩 的问题

### ISSUE THREAD

**Issue by taoyingsong** [cantonjs/wxapp-boilerplate#8]
在 `production` 环境下不想压缩怎么办，怎么没有找到压缩的配置呢

**Comment by Cap32** [comment]
把 package.json `scripts` 上 `build` 最后的 `-p` 去掉即可

**Comment by taoyingsong** [comment]
哦哦。我怎么找不到build时压缩html、js、wxss的【node插件】和【相应配置】呢，完全没有看到唉

**Comment by Cap32** [comment]
[-p](https://webpack.js.org/guides/production/) 是 webpack 内置的压缩命令规范，不同 loaders 有不同的压缩方式，优秀的 loaders 都会遵循 webpack 规范内置压缩方法。这里采用的都是各种 loaders 的默认压缩配置，所以你没有找到 “相应配置”。

**Comment by taoyingsong** [comment]
哦哦，知道了，谢谢🙏
