### ISSUE TITLE
为什么把webpack.config.babel.js修改为webpack.config.js就不能用了

### ISSUE THREAD

**Issue by taoyingsong** [cantonjs/wxapp-boilerplate#9]
默认配置文件的名字不应该是webpack.config.js吗

**Comment by Cap32** [comment]
webpack 支持配合 babel 读取 webpack.config.babel.js 文件，再配合根目录上的 .babelrc 文件将能支持使用 babel 来编写 webpack 配置文件。

**Comment by taoyingsong** [comment]
哇塞，你知道的好多啊
